# ============================================================================
# OSL: Sovereign Accounting Suite - User Registry
# ============================================================================
users:
  fonsi:
    displayname: "Paul"
    password: "$argon2id$v=19$m=65536,t=3,p=4$HSxMvM3gcoE/j99IoWR3pQ$Nd9gKc4yPbV0MScXxfqyUU6K61zsUOSuM0ud0Rrt8/k"
    email: admin@osl.net.au
    groups:
      - admins # Full tenancy and system control
